server:
  port: 8082
  servlet:
    context-path: /seckill

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 941020
  web:
    resources:
      static-locations: /WEB-INF/
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.yvonne.seckill.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql


